jms_serializer:
    handlers:
        datetime:
            default_format: "Y-m-d H:i:s"
    default_context:
        serialization:
            serialize_null: true
        deserialization:
            serialize_null: true
    visitors:
        xml:
            format_output: '%kernel.debug%'
#    metadata:
#        auto_detection: false
#        directories:
#            any-name:
#                namespace_prefix: "My\\FooBundle"
#                path: "@MyFooBundle/Resources/config/serializer"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"
